(function(){'use strict';
function e(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function c(){try{var d=getUserData();if(!d||!d.classes||!window.app||!window.app.currentClassId)return null;return d.classes.find(function(x){return x.id===window.app.currentClassId;})||null;}catch(_){return null;}}
function save(mut){try{var d=getUserData();if(!d||!d.classes||!window.app)return;var cls=d.classes.find(function(x){return x.id===window.app.currentClassId;});if(!cls)return;mut(cls);setUserData(d);}catch(_){}}
var CE={START:'#06D6A0',FINISH:'#FFD23F',NORMAL:'#f0f8ff',MINE:'#EF476F',BONUS:'#06D6A0',CARD_CHALLENGE:'#f3722c',CARD_OPPORTUNITY:'#43aa8b',CARD_REVERSE:'#577590',CARD_STEAL:'#9b5de5'};
var CI={START:'🏁',FINISH:'🏆',NORMAL:'⬜',MINE:'💣',BONUS:'🎁',CARD_CHALLENGE:'⚔️',CARD_OPPORTUNITY:'🎯',CARD_REVERSE:'🔁',CARD_STEAL:'🧲'};
window.Monopoly={
 s:{n:32,mines:[{p:6,v:-2,l:'踩坑扣2分'},{p:13,v:-3,l:'压制扣3分'},{p:20,v:-2,l:'失误扣2分'}],bonuses:[{p:4,v:3,l:'连击加3分'},{p:10,v:2,l:'协作加2分'},{p:17,v:5,l:'爆发加5分'}]},
 groups:[],cells:[],turn:0,on:false,busy:false,cardSlots:{},
 cfg:function(){var cls=c()||{};return{rollCost:Math.max(0,parseInt((document.getElementById('monopolyRollCost')&&document.getElementById('monopolyRollCost').value)||cls.monopolyRollCost,10)||1),challengePoints:Math.max(1,parseInt(cls.monopolyChallengePoints,10)||3),opportunityTask:cls.monopolyOpportunityTask||'全组完成一个互动挑战',opportunityPoints:Math.max(1,parseInt(cls.monopolyOpportunityPoints,10)||4),stealPoints:Math.max(1,parseInt(cls.monopolyStealPoints,10)||2)};},
 loadG:function(){var cls=c(),raw=(cls&&Array.isArray(cls.groups))?cls.groups:[],cols=['#FF6B35','#1B98F5','#06D6A0','#9B59F7','#FFD23F','#EF476F'];this.groups=raw.map(function(g,i){return{id:g.id,name:g.name||'小组',beastId:g.beastId||(window.BEASTS&&window.BEASTS[0]?window.BEASTS[0].id:'qinglong'),pos:0,lastPos:0,score:parseInt(g.points,10)||0,skip:false,color:g.color||cols[i%6]};});if(!this.groups.length)this.groups=[{id:'g1',name:'龙组',beastId:'qinglong',pos:0,lastPos:0,score:0,skip:false,color:'#FF6B35'},{id:'g2',name:'凤组',beastId:'fenghuang',pos:0,lastPos:0,score:0,skip:false,color:'#1B98F5'}];},
 shuffleCardSlots:function(){var n=this.s.n,a=[];for(var i=2;i<n-2;i++)a.push(i);a.sort(function(){return Math.random()-0.5;});this.cardSlots={challenge:a[0],opportunity:a[1],reverse:a[2],steal:a[3]};},
 build:function(){var n=this.s.n,self=this,cls=c();this.cells=[];for(var i=0;i<n;i++)this.cells.push({t:'NORMAL',l:'',v:0,customLabel:'',cardType:''});this.cells[0].t='START';this.cells[0].l='起点';this.cells[n-1].t='FINISH';this.cells[n-1].l='终点';this.s.mines.forEach(function(m){if(m.p>0&&m.p<n-1){self.cells[m.p].t='MINE';self.cells[m.p].l=m.l;self.cells[m.p].v=m.v;}});this.s.bonuses.forEach(function(b){if(b.p>0&&b.p<n-1){self.cells[b.p].t='BONUS';self.cells[b.p].l=b.l;self.cells[b.p].v=b.v;}});this.shuffleCardSlots();var map=[{k:'challenge',t:'CARD_CHALLENGE',l:'挑战卡落点'},{k:'opportunity',t:'CARD_OPPORTUNITY',l:'机会卡落点'},{k:'reverse',t:'CARD_REVERSE',l:'反转卡落点'},{k:'steal',t:'CARD_STEAL',l:'抽抽卡落点'}];map.forEach(function(x){var p=self.cardSlots[x.k];if(p&&self.cells[p]){self.cells[p].t=x.t;self.cells[p].l=x.l;self.cells[p].cardType=x.k;}});if(cls&&Array.isArray(cls.monopolyCustomCells))cls.monopolyCustomCells.forEach(function(cc){if(cc&&cc.index>0&&cc.index<n-1&&self.cells[cc.index])self.cells[cc.index].customLabel=cc.label||'';});},
 sync:function(){try{if(!window.app||!Array.isArray(window.app.groups))return;this.groups.forEach(function(g){var x=window.app.groups.find(function(k){return k.id===g.id;});if(x){x.points=g.score;x.beastId=g.beastId;}});window.app.saveStudents&&window.app.saveStudents();window.app.renderGroups&&window.app.renderGroups();}catch(_){}} ,
 editCell:function(i){if(i<=0||i>=this.cells.length-1)return;var cell=this.cells[i];var t=prompt('设置第'+i+'格内容（可写互动任务）',cell.customLabel||cell.l||'');if(t===null)return;cell.customLabel=String(t||'').trim();save(function(cls){if(!Array.isArray(cls.monopolyCustomCells))cls.monopolyCustomCells=[];var o=cls.monopolyCustomCells.find(function(x){return x.index===i;});if(o)o.label=cell.customLabel;else cls.monopolyCustomCells.push({index:i,label:cell.customLabel});});this.log('📝 已更新第'+i+'格：'+(cell.customLabel||'空'),'#8f8f8f');this.render();},
 render:function(){if(!this.on)this.loadG();if(!this.cells.length)this.build();var b=document.getElementById('monopolyBoard');if(!b)return;var n=this.cells.length,self=this;b.style.gridTemplateColumns='repeat(8,1fr)';b.innerHTML='';for(var i=0;i<n;i++){var c0=this.cells[i],co=CE[c0.t]||'#f0f8ff',d=document.createElement('div'),lb=c0.customLabel||c0.l;d.className='monopoly-cell';d.style.background=co+'22';d.style.borderColor=co;d.style.cursor=(i>0&&i<n-1)?'pointer':'default';var here=this.groups.filter(function(g){return g.pos===i;});var pw=here.map(function(g){var img=window.app&&window.app.getBeastPhoto?window.app.getBeastPhoto(g.beastId,5):'';return '<div class="mp-pawn" style="border-color:'+g.color+'"><img src="'+img+'" style="width:26px;height:26px;border-radius:50%;object-fit:cover" onerror="this.style.display=\'none\'"></div>';}).join('');d.innerHTML='<span class="mp-num">'+i+'</span><span class="mp-ico">'+(c0.customLabel?'🃏':(CI[c0.t]||'⬜'))+'</span><span class="mp-lbl">'+e(lb||'')+'</span><div class="mp-pawns">'+pw+'</div>';if(c0.cardType)d.style.boxShadow='inset 0 0 0 2px '+(co||'#ddd');if(here.length)d.style.boxShadow='0 0 10px '+here[0].color;(function(ix){if(ix>0&&ix<n-1)d.addEventListener('click',function(){self.editCell(ix);});})(i);b.appendChild(d);}this.side();this.topBar();},
 topBar:function(){var el=document.getElementById('monopolyInteractionBar');if(!el)return;var g=this.groups.length?this.groups[this.turn%this.groups.length]:null;var slots=this.cardSlots||{};el.innerHTML='<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;"><strong style="color:#8B1A1A;">🔥 当前互动：'+e(g?g.name:'--')+'</strong><button class="btn btn-small btn-secondary" onclick="Monopoly.card(\'challenge\')">⚔️ 挑战卡</button><button class="btn btn-small btn-secondary" onclick="Monopoly.card(\'opportunity\')">🎯 机会卡</button><button class="btn btn-small btn-secondary" onclick="Monopoly.card(\'reverse\')">🔁 反转卡</button><button class="btn btn-small btn-secondary" onclick="Monopoly.card(\'steal\')">🧲 抽抽卡</button><span style="font-size:12px;color:#777;">落点：⚔️'+(slots.challenge||'-')+' 🎯'+(slots.opportunity||'-')+' 🔁'+(slots.reverse||'-')+' 🧲'+(slots.steal||'-')+'</span></div>';},
 side:function(){var el=document.getElementById('monopolyGroupsList');if(!el)return;var self=this,ai=this.turn%Math.max(this.groups.length,1),cfg=this.cfg();el.innerHTML=this.groups.map(function(g,i){var img=window.app&&window.app.getBeastPhoto?window.app.getBeastPhoto(g.beastId,5):'';var bd=(self.on&&i===ai)?'border:3px solid '+g.color:'border:2px solid #eee';return '<div class="mp-group-card" style="'+bd+'"><img src="'+img+'" style="width:40px;height:40px;border-radius:50%;object-fit:cover" onerror="this.style.display=\'none\'"><div><strong>'+e(g.name)+'</strong><br><span style="color:'+g.color+'">⭐'+g.score+'分 📍第'+g.pos+'格</span>'+(g.skip?'<span style="color:#EF476F"> ⏭跳过</span>':'')+'</div></div>';}).join('');if(!this.on){this.groups.forEach(function(g,i){var opts=(window.BEASTS||[]).map(function(b){return '<option value="'+b.id+'"'+(b.id===g.beastId?' selected':'')+'>'+b.icon+' '+b.name+'</option>';}).join('');el.innerHTML+='<div style="margin-top:6px"><label>'+e(g.name)+'：</label><select onchange="Monopoly.setGroupBeast('+i+',this.value)">'+opts+'</select></div>';});}var info=document.getElementById('monopolyTurnInfo'),rb=document.getElementById('monopolyRollBtn'),hint=document.getElementById('monopolyCardHint');if(info&&this.on){var g0=this.groups[ai];if(g0)info.innerHTML='<strong style="color:'+g0.color+'">'+e(g0.name)+'</strong> 的回合！'+(g0.skip?'<br><span style="color:#EF476F">本回合跳过</span>':'');}else if(info)info.innerHTML='<p style="color:#888">点击「开始游戏」</p>';if(hint)hint.textContent='卡片落点每局自动重洗：挑战/机会/反转/抽抽 各1个';if(rb)rb.disabled=!this.on;},
 setGroupBeast:function(i,id){var g=this.groups[i];if(!g)return;g.beastId=id;this.sync();this.render();},
 startGame:function(){this.loadG();this.build();this.groups.forEach(function(g){g.pos=0;g.lastPos=0;g.skip=false;});this.turn=0;this.on=true;this.render();this.log('🎮 游戏开始！卡片落点已重洗','#FF6B35');},
 resetGame:function(){this.on=false;this.turn=0;this.cells=[];this.cardSlots={};this.groups.forEach(function(g){g.pos=0;g.lastPos=0;g.skip=false;});this.sync();this.render();this.log('🔄 重置','#888');},
 rollDice:function(){if(!this.on||this.busy)return;var ai=this.turn%this.groups.length,g=this.groups[ai],self=this;if(!g)return;if(g.skip){g.skip=false;this.log(g.name+' 跳过回合',g.color);this.next();return;}var cost=this.cfg().rollCost;if((g.score||0)<cost){this.log(g.name+' 积分不足，无法掷骰（需'+cost+'分）','#EF476F');this.next();return;}g.score-=cost;this.sync();this.busy=true;var t=0,r=Math.floor(Math.random()*6)+1,de=document.getElementById('monopolyDice');var iv=setInterval(function(){if(de)de.textContent=Math.floor(Math.random()*6)+1;if(++t>18){clearInterval(iv);if(de)de.textContent=r;self.move(ai,r);self.busy=false;}},80);},
 move:function(i,s){var g=this.groups[i],n=this.cells.length,self=this,np=Math.min(g.pos+s,n-1);g.lastPos=g.pos;this.log(g.name+' 掷出'+s+'，到第'+np+'格',g.color);var cur=g.pos;function step(){cur=Math.min(cur+1,np);g.pos=cur;self.render();if(cur<np)setTimeout(step,180);else self.apply(i);}setTimeout(step,180);},
 apply:function(i){var g=this.groups[i],c0=this.cells[g.pos],self=this;if(c0.t==='FINISH'){this.log(g.name+' 到达终点！','#FFD23F');this.sync();this.win(g);return;}if(c0.customLabel)this.log('🃏 '+g.name+' 触发：'+c0.customLabel,g.color);else if(c0.t==='MINE'){g.score+=c0.v;this.log(g.name+' 踩雷：'+c0.l,'#EF476F');}else if(c0.t==='BONUS'){g.score+=c0.v;this.log(g.name+' 奖励：'+c0.l,'#06D6A0');}else if(c0.t==='CARD_CHALLENGE'){this.log(g.name+' 落在 ⚔️ 挑战卡格','#f3722c');this.card('challenge');}else if(c0.t==='CARD_OPPORTUNITY'){this.log(g.name+' 落在 🎯 机会卡格','#43aa8b');this.card('opportunity');}else if(c0.t==='CARD_REVERSE'){this.log(g.name+' 落在 🔁 反转卡格','#577590');this.card('reverse');}else if(c0.t==='CARD_STEAL'){this.log(g.name+' 落在 🧲 抽抽卡格','#9b5de5');this.card('steal');}this.sync();setTimeout(function(){self.next();},700);},
 card:function(t){if(!this.on){alert('请先开始游戏');return;}var cur=this.groups[this.turn%this.groups.length],cfg=this.cfg(),enemy=this.groups.find(function(g){return g.id!==cur.id;});if(!cur)return;if(t==='challenge'){if(!enemy)return;var ok=confirm('向 '+enemy.name+' 发起互动挑战，确定=成功');if(ok){cur.score+=cfg.challengePoints;this.log('⚔️ '+cur.name+' 挑战成功 +'+cfg.challengePoints+'分',cur.color);}else this.log('⚔️ '+cur.name+' 挑战失败','#999');}else if(t==='opportunity'){var done=confirm('机会任务：'+cfg.opportunityTask+'\n确定=完成');if(done){cur.score+=cfg.opportunityPoints;this.log('🎯 '+cur.name+' 完成机会任务 +'+cfg.opportunityPoints+'分',cur.color);}else this.log('🎯 '+cur.name+' 未完成机会任务','#999');}else if(t==='reverse'){if(!enemy)return;enemy.pos=Math.max(0,(enemy.lastPos||enemy.pos)-1);this.log('🔁 '+cur.name+' 反转 '+enemy.name+' 回退',cur.color);}else if(t==='steal'){if(!enemy)return;var take=Math.min(cfg.stealPoints,Math.max(0,enemy.score||0));enemy.score=Math.max(0,(enemy.score||0)-take);cur.score=(cur.score||0)+take;this.log('🧲 '+cur.name+' 抽取 '+enemy.name+' '+take+'分',cur.color);}this.sync();this.render();},
 useCard:function(t){return this.card(t);},
 next:function(){this.turn++;this.side();this.topBar();},
 log:function(msg,color){var el=document.getElementById('monopolyLog');if(!el)return;var d=document.createElement('div');d.style.cssText='padding:4px 8px;border-radius:6px;margin-bottom:4px;font-size:0.85rem;border-left:3px solid '+(color||'#FF6B35');d.textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})+' '+msg;el.insertBefore(d,el.firstChild);if(el.children.length>40)el.lastChild.remove();},
 win:function(g){var el=document.createElement('div');el.style.cssText='position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);z-index:10003;pointer-events:none;text-align:center;width:260px;background:#fff;border:4px solid '+g.color+';border-radius:24px;padding:30px 20px;box-shadow:0 0 60px '+g.color+'88;';el.innerHTML='<div style="font-size:3rem">🏆</div><div style="font-size:1.5rem;font-weight:bold;color:'+g.color+'">'+e(g.name)+'</div><div style="color:#888;margin-top:8px">到达终点，获得胜利！</div>';document.body.appendChild(el);setTimeout(function(){el.remove();},3200);window.launchFireworks&&window.launchFireworks();}
};
})();